<?php
/**
 * ACF Flexible Content — Page Sections
 *
 * Registers a flexible content field group for page sections (Hero, Slider, etc.).
 * Used on all pages to allow modular section composition via ACF.
 *
 * @since 1.0.0
 */

/**
 * Register the page sections flexible content field group.
 */
function rms_register_acf_page_sections(): void {
    if (!function_exists('acf_add_local_field_group')) {
        return;
    }

    acf_add_local_field_group([
        'key'    => 'group_rms_page_sections',
        'title'  => 'Page Sections',
        'fields' => [
            [
                'key'          => 'field_rms_page_sections',
                'label'        => 'Page Sections',
                'name'         => 'page_sections',
                'aria-label'   => '',
                'type'         => 'flexible_content',
                'instructions' => 'Add and reorder sections for this page.',
                'required'     => 0,
                'conditional_logic' => false,
                'wrapper'      => [
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ],
                'layouts'      => [
                    'layout_hero'   => [
                        'key'        => 'layout_hero',
                        'name'       => 'hero',
                        'label'      => 'Hero',
                        'display'    => 'block',
                        'sub_fields' => [
                            [
                                'key'           => 'field_rms_hero_bg_image',
                                'label'         => 'Background Image',
                                'name'          => 'hero_bg_image',
                                'aria-label'    => '',
                                'type'          => 'image',
                                'instructions'  => '',
                                'required'      => 0,
                                'conditional_logic' => false,
                                'wrapper'       => [
                                    'width' => '',
                                    'class' => '',
                                    'id'    => '',
                                ],
                                'return_format' => 'url',
                                'preview_size'  => 'medium',
                                'library'       => 'all',
                                'min_width'     => 0,
                                'min_height'    => 0,
                                'min_size'      => 0,
                                'max_width'     => 0,
                                'max_height'    => 0,
                                'max_size'      => 0,
                                'mime_types'    => '',
                            ],
                            [
                                'key'           => 'field_rms_hero_reviews_label',
                                'label'         => 'Reviews Label',
                                'name'          => 'hero_reviews_label',
                                'aria-label'    => '',
                                'type'          => 'text',
                                'instructions'  => '',
                                'required'      => 0,
                                'conditional_logic' => false,
                                'wrapper'       => [
                                    'width' => '50',
                                    'class' => '',
                                    'id'    => '',
                                ],
                                'placeholder'   => "e.g. 5.0 Google Reviews",
                                'default_value' => '',
                                'maxlength'     => '',
                                'prepend'       => '',
                                'append'        => '',
                            ],
                            [
                                'key'           => 'field_rms_hero_title',
                                'label'         => 'Title',
                                'name'          => 'hero_title',
                                'aria-label'    => '',
                                'type'          => 'text',
                                'instructions'  => '',
                                'required'      => 0,
                                'conditional_logic' => false,
                                'wrapper'       => [
                                    'width' => '50',
                                    'class' => '',
                                    'id'    => '',
                                ],
                                'placeholder'   => "e.g. Professional Roofing Solutions You Can Trust",
                                'default_value' => '',
                                'maxlength'     => '',
                                'prepend'       => '',
                                'append'        => '',
                            ],
                            [
                                'key'           => 'field_rms_hero_description',
                                'label'         => 'Description',
                                'name'          => 'hero_description',
                                'aria-label'    => '',
                                'type'          => 'wysiwyg',
                                'instructions'  => '',
                                'required'      => 0,
                                'conditional_logic' => false,
                                'wrapper'       => [
                                    'width' => '',
                                    'class' => '',
                                    'id'    => '',
                                ],
                                'placeholder'   => "e.g. We deliver high-quality roofing services for residential and commercial properties...",
                                'default_value' => '',
                                'tabs'          => 'visual',
                                'toolbar'       => 'basic',
                                'media_upload'  => 0,
                            ],
                            [
                                'key'           => 'field_rms_hero_form_shortcode',
                                'label'         => 'Form Shortcode',
                                'name'          => 'hero_form_shortcode',
                                'aria-label'    => '',
                                'type'          => 'text',
                                'instructions'  => 'Paste a contact form shortcode here to replace the default form.',
                                'required'      => 0,
                                'conditional_logic' => false,
                                'wrapper'       => [
                                    'width' => '',
                                    'class' => '',
                                    'id'    => '',
                                ],
                                'placeholder'   => "e.g. [contact-form-7 id='123' title='Free Estimate']",
                                'default_value' => '',
                                'maxlength'     => '',
                                'prepend'       => '',
                                'append'        => '',
                            ],
                        ],
                    ],
                    'layout_slider' => [
                        'key'        => 'layout_slider',
                        'name'       => 'slider',
                        'label'      => 'Slider',
                        'display'    => 'block',
                        'sub_fields' => [
                            [
                                'key'           => 'field_rms_slider_slides',
                                'label'         => 'Slides',
                                'name'          => 'slider_slides',
                                'aria-label'    => '',
                                'type'          => 'repeater',
                                'instructions'  => 'Add one or more slides. The first slide will use an H1 tag; subsequent slides use H2.',
                                'required'      => 0,
                                'conditional_logic' => false,
                                'wrapper'       => [
                                    'width' => '',
                                    'class' => '',
                                    'id'    => '',
                                ],
                                'layout'        => 'block',
                                'min'           => 0,
                                'max'           => 0,
                                'rows_per_page' => 20,
                                'button_label'  => 'Add Slide',
                                'collapsed'     => '',
                                'sub_fields'    => [
                                    [
                                        'key'           => 'field_rms_slide_bg_image',
                                        'label'         => 'Background Image',
                                        'name'          => 'slide_bg_image',
                                        'aria-label'    => '',
                                        'type'          => 'image',
                                        'instructions'  => '',
                                        'required'      => 0,
                                        'conditional_logic' => false,
                                        'wrapper'       => [
                                            'width' => '',
                                            'class' => '',
                                            'id'    => '',
                                        ],
                                        'return_format' => 'url',
                                        'preview_size'  => 'medium',
                                        'library'       => 'all',
                                        'min_width'     => 0,
                                        'min_height'    => 0,
                                        'min_size'      => 0,
                                        'max_width'     => 0,
                                        'max_height'    => 0,
                                        'max_size'      => 0,
                                        'mime_types'    => '',
                                        'parent_repeater' => 'field_rms_slider_slides',
                                    ],
                                    [
                                        'key'           => 'field_rms_slide_subheadline',
                                        'label'         => 'Subheadline',
                                        'name'          => 'slide_subheadline',
                                        'aria-label'    => '',
                                        'type'          => 'text',
                                        'instructions'  => '',
                                        'required'      => 0,
                                        'conditional_logic' => false,
                                        'wrapper'       => [
                                            'width' => '50',
                                            'class' => '',
                                            'id'    => '',
                                        ],
                                        'placeholder'   => "e.g. Trusted Roofing Experts",
                                        'default_value' => '',
                                        'maxlength'     => '',
                                        'prepend'       => '',
                                        'append'        => '',
                                        'parent_repeater' => 'field_rms_slider_slides',
                                    ],
                                    [
                                        'key'           => 'field_rms_slide_headline',
                                        'label'         => 'Headline',
                                        'name'          => 'slide_headline',
                                        'aria-label'    => '',
                                        'type'          => 'text',
                                        'instructions'  => '',
                                        'required'      => 0,
                                        'conditional_logic' => false,
                                        'wrapper'       => [
                                            'width' => '50',
                                            'class' => '',
                                            'id'    => '',
                                        ],
                                        'placeholder'   => "e.g. Protecting What Matters Most",
                                        'default_value' => '',
                                        'maxlength'     => '',
                                        'prepend'       => '',
                                        'append'        => '',
                                        'parent_repeater' => 'field_rms_slider_slides',
                                    ],
                                    [
                                        'key'           => 'field_rms_slide_text',
                                        'label'         => 'Text',
                                        'name'          => 'slide_text',
                                        'aria-label'    => '',
                                        'type'          => 'wysiwyg',
                                        'instructions'  => '',
                                        'required'      => 0,
                                        'conditional_logic' => false,
                                        'wrapper'       => [
                                            'width' => '',
                                            'class' => '',
                                            'id'    => '',
                                        ],
                                        'placeholder'   => "e.g. We deliver premium roofing solutions...",
                                        'default_value' => '',
                                        'tabs'          => 'visual',
                                        'toolbar'       => 'basic',
                                        'media_upload'  => 0,
                                        'parent_repeater' => 'field_rms_slider_slides',
                                    ],
                                    [
                                        'key'           => 'field_rms_slide_cta_text',
                                        'label'         => 'CTA Text',
                                        'name'          => 'slide_cta_text',
                                        'aria-label'    => '',
                                        'type'          => 'text',
                                        'instructions'  => '',
                                        'required'      => 0,
                                        'conditional_logic' => false,
                                        'wrapper'       => [
                                            'width' => '50',
                                            'class' => '',
                                            'id'    => '',
                                        ],
                                        'placeholder'   => "e.g. Get Free Estimate",
                                        'default_value' => '',
                                        'maxlength'     => '',
                                        'prepend'       => '',
                                        'append'        => '',
                                        'parent_repeater' => 'field_rms_slider_slides',
                                    ],
                                    [
                                        'key'           => 'field_rms_slide_cta_url',
                                        'label'         => 'CTA URL',
                                        'name'          => 'slide_cta_url',
                                        'aria-label'    => '',
                                        'type'          => 'url',
                                        'instructions'  => '',
                                        'required'      => 0,
                                        'conditional_logic' => false,
                                        'wrapper'       => [
                                            'width' => '50',
                                            'class' => '',
                                            'id'    => '',
                                        ],
                                        'placeholder'   => "e.g. #estimate",
                                        'default_value' => '',
                                        'parent_repeater' => 'field_rms_slider_slides',
                                    ],
                                ],
                            ],
                        ],
                    ],
                    'layout_about_us' => [
                        'key'        => 'layout_about_us',
                        'name'       => 'about-us',
                        'label'      => 'About Us',
                        'display'    => 'block',
                        'sub_fields' => [
                            [
                                'key'           => 'field_rms_about_headline',
                                'label'         => 'Headline',
                                'name'          => 'about_headline',
                                'aria-label'    => '',
                                'type'          => 'text',
                                'instructions'  => '',
                                'required'      => 0,
                                'conditional_logic' => false,
                                'wrapper'       => [
                                    'width' => '100',
                                    'class' => '',
                                    'id'    => '',
                                ],
                                'placeholder'   => "e.g. We Are The Best Roofing Company",
                                'default_value' => '',
                                'maxlength'     => '',
                                'prepend'       => '',
                                'append'        => '',
                            ],
                            [
                                'key'           => 'field_rms_about_subheadline',
                                'label'         => 'Subheadline',
                                'name'          => 'about_subheadline',
                                'aria-label'    => '',
                                'type'          => 'text',
                                'instructions'  => '',
                                'required'      => 0,
                                'conditional_logic' => false,
                                'wrapper'       => [
                                    'width' => '100',
                                    'class' => '',
                                    'id'    => '',
                                ],
                                'placeholder'   => "e.g. Trusted by Homeowners Across the Region",
                                'default_value' => '',
                                'maxlength'     => '',
                                'prepend'       => '',
                                'append'        => '',
                            ],
                            [
                                'key'           => 'field_rms_about_text',
                                'label'         => 'Text',
                                'name'          => 'about_text',
                                'aria-label'    => '',
                                'type'          => 'wysiwyg',
                                'instructions'  => '',
                                'required'      => 0,
                                'conditional_logic' => false,
                                'wrapper'       => [
                                    'width' => '',
                                    'class' => '',
                                    'id'    => '',
                                ],
                                'placeholder'   => "e.g. With decades of hands-on experience...",
                                'default_value' => '',
                                'tabs'          => 'visual',
                                'toolbar'       => 'basic',
                                'media_upload'  => 0,
                            ],
                            [
                                'key'           => 'field_rms_about_image',
                                'label'         => 'Image',
                                'name'          => 'about_image',
                                'aria-label'    => '',
                                'type'          => 'image',
                                'instructions'  => '',
                                'required'      => 0,
                                'conditional_logic' => false,
                                'wrapper'       => [
                                    'width' => '',
                                    'class' => '',
                                    'id'    => '',
                                ],
                                'return_format' => 'url',
                                'preview_size'  => 'medium',
                                'library'       => 'all',
                                'min_width'     => 0,
                                'min_height'    => 0,
                                'min_size'      => 0,
                                'max_width'     => 0,
                                'max_height'    => 0,
                                'max_size'      => 0,
                                'mime_types'    => '',
                            ],
                            [
                                'key'           => 'field_rms_about_badge_years',
                                'label'         => 'Badge Years',
                                'name'          => 'about_badge_years',
                                'aria-label'    => '',
                                'type'          => 'text',
                                'instructions'  => '',
                                'required'      => 0,
                                'conditional_logic' => false,
                                'wrapper'       => [
                                    'width' => '50',
                                    'class' => '',
                                    'id'    => '',
                                ],
                                'placeholder'   => "e.g. 25",
                                'default_value' => '',
                                'maxlength'     => '',
                                'prepend'       => '',
                                'append'        => '',
                            ],
                            [
                                'key'           => 'field_rms_about_badge_label',
                                'label'         => 'Badge Label',
                                'name'          => 'about_badge_label',
                                'aria-label'    => '',
                                'type'          => 'text',
                                'instructions'  => '',
                                'required'      => 0,
                                'conditional_logic' => false,
                                'wrapper'       => [
                                    'width' => '50',
                                    'class' => '',
                                    'id'    => '',
                                ],
                                'placeholder'   => "e.g. Years Of Experience",
                                'default_value' => '',
                                'maxlength'     => '',
                                'prepend'       => '',
                                'append'        => '',
                            ],
                        ],
                    ],
                    'layout_area_coverage_v1' => [
                        'key'        => 'layout_area_coverage_v1',
                        'name'       => 'area-coverage-v1',
                        'label'      => 'Area Coverage V1',
                        'display'    => 'block',
                        'sub_fields' => [
                            [
                                'key'           => 'field_rms_area_eyebrow',
                                'label'         => 'Eyebrow',
                                'name'          => 'area_eyebrow',
                                'aria-label'    => '',
                                'type'          => 'text',
                                'instructions'  => '',
                                'required'      => 0,
                                'conditional_logic' => false,
                                'wrapper'       => [
                                    'width' => '50',
                                    'class' => '',
                                    'id'    => '',
                                ],
                                'placeholder'   => "e.g. Regional Coverage",
                                'default_value' => '',
                                'maxlength'     => '',
                                'prepend'       => '',
                                'append'        => '',
                            ],
                            [
                                'key'           => 'field_rms_area_headline',
                                'label'         => 'Headline',
                                'name'          => 'area_headline',
                                'aria-label'    => '',
                                'type'          => 'text',
                                'instructions'  => '',
                                'required'      => 0,
                                'conditional_logic' => false,
                                'wrapper'       => [
                                    'width' => '50',
                                    'class' => '',
                                    'id'    => '',
                                ],
                                'placeholder'   => "e.g. Areas We Proudly Serve",
                                'default_value' => '',
                                'maxlength'     => '',
                                'prepend'       => '',
                                'append'        => '',
                            ],
                            [
                                'key'           => 'field_rms_area_description',
                                'label'         => 'Description',
                                'name'          => 'area_description',
                                'aria-label'    => '',
                                'type'          => 'wysiwyg',
                                'instructions'  => '',
                                'required'      => 0,
                                'conditional_logic' => false,
                                'wrapper'       => [
                                    'width' => '',
                                    'class' => '',
                                    'id'    => '',
                                ],
                                'placeholder'   => '',
                                'default_value' => '',
                                'tabs'          => 'visual',
                                'toolbar'       => 'basic',
                                'media_upload'  => 0,
                            ],
                            [
                                'key'           => 'field_rms_area_radius',
                                'label'         => 'Service Radius',
                                'name'          => 'area_radius',
                                'aria-label'    => '',
                                'type'          => 'text',
                                'instructions'  => '',
                                'required'      => 0,
                                'conditional_logic' => false,
                                'wrapper'       => [
                                    'width' => '50',
                                    'class' => '',
                                    'id'    => '',
                                ],
                                'placeholder'   => "e.g. 50 Miles",
                                'default_value' => '',
                                'maxlength'     => '',
                                'prepend'       => '',
                                'append'        => '',
                            ],
                            [
                                'key'           => 'field_rms_area_cities',
                                'label'         => 'Cities',
                                'name'          => 'area_cities',
                                'aria-label'    => '',
                                'type'          => 'repeater',
                                'instructions'  => '',
                                'required'      => 0,
                                'conditional_logic' => false,
                                'wrapper'       => [
                                    'width' => '',
                                    'class' => '',
                                    'id'    => '',
                                ],
                                'layout'        => 'block',
                                'min'           => 0,
                                'max'           => 0,
                                'rows_per_page' => 20,
                                'button_label'  => 'Add City',
                                'collapsed'     => '',
                                'sub_fields'    => [
                                    [
                                        'key'           => 'field_rms_area_city_name',
                                        'label'         => 'City Name',
                                        'name'          => 'city_name',
                                        'aria-label'    => '',
                                        'type'          => 'text',
                                        'instructions'  => '',
                                        'required'      => 0,
                                        'conditional_logic' => false,
                                        'wrapper'       => [
                                            'width' => '100',
                                            'class' => '',
                                            'id'    => '',
                                        ],
                                        'placeholder'   => "e.g. Orlando",
                                        'default_value' => '',
                                        'maxlength'     => '',
                                        'prepend'       => '',
                                        'append'        => '',
                                        'parent_repeater' => 'field_rms_area_cities',
                                    ],
                                ],
                            ],
                            [
                                'key'           => 'field_rms_area_cta_text',
                                'label'         => 'CTA Text',
                                'name'          => 'area_cta_text',
                                'aria-label'    => '',
                                'type'          => 'text',
                                'instructions'  => '',
                                'required'      => 0,
                                'conditional_logic' => false,
                                'wrapper'       => [
                                    'width' => '50',
                                    'class' => '',
                                    'id'    => '',
                                ],
                                'placeholder'   => "e.g. Check Your Location",
                                'default_value' => '',
                                'maxlength'     => '',
                                'prepend'       => '',
                                'append'        => '',
                            ],
                            [
                                'key'           => 'field_rms_area_cta_url',
                                'label'         => 'CTA URL',
                                'name'          => 'area_cta_url',
                                'aria-label'    => '',
                                'type'          => 'url',
                                'instructions'  => '',
                                'required'      => 0,
                                'conditional_logic' => false,
                                'wrapper'       => [
                                    'width' => '50',
                                    'class' => '',
                                    'id'    => '',
                                ],
                                'placeholder'   => "e.g. #contact",
                                'default_value' => '',
                            ],
                            [
                                'key'           => 'field_rms_area_map_image',
                                'label'         => 'Map Image',
                                'name'          => 'area_map_image',
                                'aria-label'    => '',
                                'type'          => 'image',
                                'instructions'  => '',
                                'required'      => 0,
                                'conditional_logic' => false,
                                'wrapper'       => [
                                    'width' => '',
                                    'class' => '',
                                    'id'    => '',
                                ],
                                'return_format' => 'url',
                                'preview_size'  => 'medium',
                                'library'       => 'all',
                                'min_width'     => 0,
                                'min_height'    => 0,
                                'min_size'      => 0,
                                'max_width'     => 0,
                                'max_height'    => 0,
                                'max_size'      => 0,
                                'mime_types'    => '',
                            ],
                        ],
                    ],
                    'layout_badges' => [
                        'key'        => 'layout_badges',
                        'name'       => 'badges',
                        'label'      => 'Badges',
                        'display'    => 'block',
                        'sub_fields' => [
                            [
                                'key'           => 'field_rms_badge_label',
                                'label'         => 'Label',
                                'name'          => 'badges_label',
                                'aria-label'    => '',
                                'type'          => 'text',
                                'instructions'  => '',
                                'required'      => 0,
                                'conditional_logic' => false,
                                'wrapper'       => [
                                    'width' => '',
                                    'class' => '',
                                    'id'    => '',
                                ],
                                'placeholder'   => "e.g. Trusted & Verified On",
                                'default_value' => '',
                                'maxlength'     => '',
                                'prepend'       => '',
                                'append'        => '',
                            ],
                            [
                                'key'           => 'field_rms_badge_items',
                                'label'         => 'Badges',
                                'name'          => 'badges_items',
                                'aria-label'    => '',
                                'type'          => 'repeater',
                                'instructions'  => '',
                                'required'      => 0,
                                'conditional_logic' => false,
                                'wrapper'       => [
                                    'width' => '',
                                    'class' => '',
                                    'id'    => '',
                                ],
                                'layout'        => 'block',
                                'min'           => 0,
                                'max'           => 0,
                                'rows_per_page' => 20,
                                'button_label'  => 'Add Badge',
                                'collapsed'     => '',
                                'sub_fields'    => [
                                    [
                                        'key'           => 'field_rms_badge_item_icon',
                                        'label'         => 'Icon',
                                        'name'          => 'badge_icon',
                                        'aria-label'    => '',
                                        'type'          => 'text',
                                        'instructions'  => '',
                                        'required'      => 0,
                                        'conditional_logic' => false,
                                        'wrapper'       => [
                                            'width' => '50',
                                            'class' => '',
                                            'id'    => '',
                                        ],
                                        'placeholder'   => "e.g. BBB, HA, YP",
                                        'default_value' => '',
                                        'maxlength'     => '',
                                        'prepend'       => '',
                                        'append'        => '',
                                        'parent_repeater' => 'field_rms_badge_items',
                                    ],
                                    [
                                        'key'           => 'field_rms_badge_item_name',
                                        'label'         => 'Name',
                                        'name'          => 'badge_name',
                                        'aria-label'    => '',
                                        'type'          => 'text',
                                        'instructions'  => '',
                                'required'      => 0,
                                        'conditional_logic' => false,
                                        'wrapper'       => [
                                            'width' => '50',
                                            'class' => '',
                                            'id'    => '',
                                        ],
                                        'placeholder'   => "e.g. BBB Accredited",
                                        'default_value' => '',
                                        'maxlength'     => '',
                                        'prepend'       => '',
                                        'append'        => '',
                                        'parent_repeater' => 'field_rms_badge_items',
                                    ],
                                    [
                                        'key'           => 'field_rms_badge_url',
                                        'label'         => 'Badge URL',
                                        'name'          => 'badge_url',
                                        'aria-label'    => '',
                                        'type'          => 'url',
                                        'instructions'  => '',
                                        'required'      => 0,
                                        'conditional_logic' => false,
                                        'wrapper'       => [
                                            'width' => '100',
                                            'class' => '',
                                            'id'    => '',
                                        ],
                                        'placeholder'   => 'e.g. https://www.bbb.org/your-business',
                                        'default_value' => '',
                                        'parent_repeater' => 'field_rms_badge_items',
                                    ],
                                ],
                            ],
                        ],
                    ],
                    'layout_blog_v1' => [
                        'key'        => 'layout_blog_v1',
                        'name'       => 'blog-v1',
                        'label'      => 'Blog V1',
                        'display'    => 'block',
                        'sub_fields' => [
                            [
                                'key'           => 'field_rms_blog_headline',
                                'label'         => 'Headline',
                                'name'          => 'blog_headline',
                                'aria-label'    => '',
                                'type'          => 'text',
                                'instructions'  => '',
                                'required'      => 0,
                                'conditional_logic' => false,
                                'wrapper'       => [
                                    'width' => '50',
                                    'class' => '',
                                    'id'    => '',
                                ],
                                'placeholder'   => "e.g. Latest Blog Posts",
                                'default_value' => '',
                                'maxlength'     => '',
                                'prepend'       => '',
                                'append'        => '',
                            ],
                            [
                                'key'           => 'field_rms_blog_cta_text',
                                'label'         => 'CTA Text',
                                'name'          => 'blog_cta_text',
                                'aria-label'    => '',
                                'type'          => 'text',
                                'instructions'  => '',
                                'required'      => 0,
                                'conditional_logic' => false,
                                'wrapper'       => [
                                    'width' => '50',
                                    'class' => '',
                                    'id'    => '',
                                ],
                                'placeholder'   => "e.g. Read More Blog Posts",
                                'default_value' => '',
                                'maxlength'     => '',
                                'prepend'       => '',
                                'append'        => '',
                            ],
                            [
                                'key'           => 'field_rms_blog_cta_url',
                                'label'         => 'CTA URL',
                                'name'          => 'blog_cta_url',
                                'aria-label'    => '',
                                'type'          => 'url',
                                'instructions'  => '',
                                'required'      => 0,
                                'conditional_logic' => false,
                                'wrapper'       => [
                                    'width' => '50',
                                    'class' => '',
                                    'id'    => '',
                                ],
                                'placeholder'   => "e.g. /blog/",
                                'default_value' => '',
                            ],
                        ],
                    ],
                    'layout_contact_info' => [
                        'key'        => 'layout_contact_info',
                        'name'       => 'contact-info',
                        'label'      => 'Contact Info',
                        'display'    => 'block',
                        'sub_fields' => [
                            [
                                'key'           => 'field_rms_contact_info_headline',
                                'label'         => 'Headline',
                                'name'          => 'contact_info_headline',
                                'aria-label'    => '',
                                'type'          => 'text',
                                'instructions'  => '',
                                'required'      => 0,
                                'conditional_logic' => false,
                                'wrapper'       => [
                                    'width' => '50',
                                    'class' => '',
                                    'id'    => '',
                                ],
                                'placeholder'   => "e.g. Get in Touch",
                                'default_value' => '',
                                'maxlength'     => '',
                                'prepend'       => '',
                                'append'        => '',
                            ],
                            [
                                'key'           => 'field_rms_contact_info_intro',
                                'label'         => 'Intro',
                                'name'          => 'contact_info_intro',
                                'aria-label'    => '',
                                'type'          => 'wysiwyg',
                                'instructions'  => '',
                                'required'      => 0,
                                'conditional_logic' => false,
                                'wrapper'       => [
                                    'width' => '',
                                    'class' => '',
                                    'id'    => '',
                                ],
                                'placeholder'   => '',
                                'default_value' => '',
                                'tabs'          => 'visual',
                                'toolbar'       => 'basic',
                                'media_upload'  => 0,
                            ],
                            [
                                'key'           => 'field_rms_contact_info_form_shortcode',
                                'label'         => 'Form Shortcode',
                                'name'          => 'contact_info_form_shortcode',
                                'aria-label'    => '',
                                'type'          => 'text',
                                'instructions'  => 'Paste a contact form shortcode. Leave empty to use the default form.',
                                'required'      => 0,
                                'conditional_logic' => false,
                                'wrapper'       => [
                                    'width' => '',
                                    'class' => '',
                                    'id'    => '',
                                ],
                                'placeholder'   => "e.g. [contact-form-7 id='123' title='Contact']",
                                'default_value' => '',
                                'maxlength'     => '',
                                'prepend'       => '',
                                'append'        => '',
                            ],
                        ],
                    ],
                    'layout_cta_v1' => [
                        'key'        => 'layout_cta_v1',
                        'name'       => 'cta-v1',
                        'label'      => 'CTA V1',
                        'display'    => 'block',
                        'sub_fields' => [
                            [
                                'key'           => 'field_rms_cta_v1_headline',
                                'label'         => 'Headline',
                                'name'          => 'cta_v1_headline',
                                'aria-label'    => '',
                                'type'          => 'text',
                                'instructions'  => '',
                                'required'      => 0,
                                'conditional_logic' => false,
                                'wrapper'       => [
                                    'width' => '50',
                                    'class' => '',
                                    'id'    => '',
                                ],
                                'placeholder'   => "e.g. Ready to Protect Your Home?",
                                'default_value' => '',
                                'maxlength'     => '',
                                'prepend'       => '',
                                'append'        => '',
                            ],
                            [
                                'key'           => 'field_rms_cta_v1_text',
                                'label'         => 'Text',
                                'name'          => 'cta_v1_text',
                                'aria-label'    => '',
                                'type'          => 'text',
                                'instructions'  => '',
                                'required'      => 0,
                                'conditional_logic' => false,
                                'wrapper'       => [
                                    'width' => '50',
                                    'class' => '',
                                    'id'    => '',
                                ],
                                'placeholder'   => "e.g. Get a free inspection and estimate today.",
                                'default_value' => '',
                                'maxlength'     => '',
                                'prepend'       => '',
                                'append'        => '',
                            ],
                            [
                                'key'           => 'field_rms_cta_v1_button_text',
                                'label'         => 'Button Text',
                                'name'          => 'cta_v1_button_text',
                                'aria-label'    => '',
                                'type'          => 'text',
                                'instructions'  => '',
                                'required'      => 0,
                                'conditional_logic' => false,
                                'wrapper'       => [
                                    'width' => '50',
                                    'class' => '',
                                    'id'    => '',
                                ],
                                'placeholder'   => "e.g. Get Your Free Estimate",
                                'default_value' => '',
                                'maxlength'     => '',
                                'prepend'       => '',
                                'append'        => '',
                            ],
                            [
                                'key'           => 'field_rms_cta_v1_button_url',
                                'label'         => 'Button URL',
                                'name'          => 'cta_v1_button_url',
                                'aria-label'    => '',
                                'type'          => 'url',
                                'instructions'  => '',
                                'required'      => 0,
                                'conditional_logic' => false,
                                'wrapper'       => [
                                    'width' => '50',
                                    'class' => '',
                                    'id'    => '',
                                ],
                                'placeholder'   => "e.g. #contact",
                                'default_value' => '',
                            ],
                        ],
                    ],
                    'layout_cta_v2' => [
                        'key'        => 'layout_cta_v2',
                        'name'       => 'cta-v2',
                        'label'      => 'CTA V2',
                        'display'    => 'block',
                        'sub_fields' => [
                            [
                                'key'           => 'field_rms_cta_v2_headline',
                                'label'         => 'Headline',
                                'name'          => 'cta_v2_headline',
                                'aria-label'    => '',
                                'type'          => 'text',
                                'instructions'  => '',
                                'required'      => 0,
                                'conditional_logic' => false,
                                'wrapper'       => [
                                    'width' => '50',
                                    'class' => '',
                                    'id'    => '',
                                ],
                                'placeholder'   => "e.g. Let's Build Something Great Together",
                                'default_value' => '',
                                'maxlength'     => '',
                                'prepend'       => '',
                                'append'        => '',
                            ],
                            [
                                'key'           => 'field_rms_cta_v2_text',
                                'label'         => 'Text',
                                'name'          => 'cta_v2_text',
                                'aria-label'    => '',
                                'type'          => 'text',
                                'instructions'  => '',
                                'required'      => 0,
                                'conditional_logic' => false,
                                'wrapper'       => [
                                    'width' => '50',
                                    'class' => '',
                                    'id'    => '',
                                ],
                                'placeholder'   => "e.g. Contact us today to discuss your project.",
                                'default_value' => '',
                                'maxlength'     => '',
                                'prepend'       => '',
                                'append'        => '',
                            ],
                            [
                                'key'           => 'field_rms_cta_v2_primary_text',
                                'label'         => 'Primary Button Text',
                                'name'          => 'cta_v2_primary_text',
                                'aria-label'    => '',
                                'type'          => 'text',
                                'instructions'  => '',
                                'required'      => 0,
                                'conditional_logic' => false,
                                'wrapper'       => [
                                    'width' => '50',
                                    'class' => '',
                                    'id'    => '',
                                ],
                                'placeholder'   => "e.g. Free Estimate",
                                'default_value' => '',
                                'maxlength'     => '',
                                'prepend'       => '',
                                'append'        => '',
                            ],
                            [
                                'key'           => 'field_rms_cta_v2_primary_url',
                                'label'         => 'Primary Button URL',
                                'name'          => 'cta_v2_primary_url',
                                'aria-label'    => '',
                                'type'          => 'url',
                                'instructions'  => '',
                                'required'      => 0,
                                'conditional_logic' => false,
                                'wrapper'       => [
                                    'width' => '50',
                                    'class' => '',
                                    'id'    => '',
                                ],
                                'placeholder'   => "e.g. #contact",
                                'default_value' => '',
                            ],
                            [
                                'key'           => 'field_rms_cta_v2_secondary_text',
                                'label'         => 'Secondary Button Text',
                                'name'          => 'cta_v2_secondary_text',
                                'aria-label'    => '',
                                'type'          => 'text',
                                'instructions'  => '',
                                'required'      => 0,
                                'conditional_logic' => false,
                                'wrapper'       => [
                                    'width' => '50',
                                    'class' => '',
                                    'id'    => '',
                                ],
                                'placeholder'   => "e.g. Call Now",
                                'default_value' => '',
                                'maxlength'     => '',
                                'prepend'       => '',
                                'append'        => '',
                            ],
                            [
                                'key'           => 'field_rms_cta_v2_secondary_url',
                                'label'         => 'Secondary Button URL',
                                'name'          => 'cta_v2_secondary_url',
                                'aria-label'    => '',
                                'type'          => 'url',
                                'instructions'  => '',
                                'required'      => 0,
                                'conditional_logic' => false,
                                'wrapper'       => [
                                    'width' => '50',
                                    'class' => '',
                                    'id'    => '',
                                ],
                                'placeholder'   => "e.g. tel:+1234567890",
                                'default_value' => '',
                            ],
                        ],
                    ],
                    'layout_cta_v3' => [
                        'key'        => 'layout_cta_v3',
                        'name'       => 'cta-v3',
                        'label'      => 'CTA V3',
                        'display'    => 'block',
                        'sub_fields' => [
                            [
                                'key'           => 'field_rms_cta_v3_headline',
                                'label'         => 'Headline',
                                'name'          => 'cta_v3_headline',
                                'aria-label'    => '',
                                'type'          => 'text',
                                'instructions'  => '',
                                'required'      => 0,
                                'conditional_logic' => false,
                                'wrapper'       => [
                                    'width' => '',
                                    'class' => '',
                                    'id'    => '',
                                ],
                                'placeholder'   => "e.g. Join Our Growing List of Happy Homeowners",
                                'default_value' => '',
                                'maxlength'     => '',
                                'prepend'       => '',
                                'append'        => '',
                            ],
                            [
                                'key'           => 'field_rms_cta_v3_button_text',
                                'label'         => 'Button Text',
                                'name'          => 'cta_v3_button_text',
                                'aria-label'    => '',
                                'type'          => 'text',
                                'instructions'  => '',
                                'required'      => 0,
                                'conditional_logic' => false,
                                'wrapper'       => [
                                    'width' => '50',
                                    'class' => '',
                                    'id'    => '',
                                ],
                                'placeholder'   => "e.g. Start Your Project Today",
                                'default_value' => '',
                                'maxlength'     => '',
                                'prepend'       => '',
                                'append'        => '',
                            ],
                            [
                                'key'           => 'field_rms_cta_v3_button_url',
                                'label'         => 'Button URL',
                                'name'          => 'cta_v3_button_url',
                                'aria-label'    => '',
                                'type'          => 'url',
                                'instructions'  => '',
                                'required'      => 0,
                                'conditional_logic' => false,
                                'wrapper'       => [
                                    'width' => '50',
                                    'class' => '',
                                    'id'    => '',
                                ],
                                'placeholder'   => "e.g. #contact",
                                'default_value' => '',
                            ],
                            [
                                'key'           => 'field_rms_cta_v3_stats',
                                'label'         => 'Stats',
                                'name'          => 'cta_v3_stats',
                                'aria-label'    => '',
                                'type'          => 'repeater',
                                'instructions'  => '',
                                'required'      => 0,
                                'conditional_logic' => false,
                                'wrapper'       => [
                                    'width' => '',
                                    'class' => '',
                                    'id'    => '',
                                ],
                                'layout'        => 'block',
                                'min'           => 0,
                                'max'           => 0,
                                'rows_per_page' => 20,
                                'button_label'  => 'Add Stat',
                                'collapsed'     => '',
                                'sub_fields'    => [
                                    [
                                        'key'           => 'field_rms_cta_v3_stat_number',
                                        'label'         => 'Stat Number',
                                        'name'          => 'stat_number',
                                        'aria-label'    => '',
                                        'type'          => 'text',
                                        'instructions'  => '',
                                        'required'      => 0,
                                        'conditional_logic' => false,
                                        'wrapper'       => [
                                            'width' => '50',
                                            'class' => '',
                                            'id'    => '',
                                        ],
                                        'placeholder'   => "e.g. 500+",
                                        'default_value' => '',
                                        'maxlength'     => '',
                                        'prepend'       => '',
                                        'append'        => '',
                                        'parent_repeater' => 'field_rms_cta_v3_stats',
                                    ],
                                    [
                                        'key'           => 'field_rms_cta_v3_stat_label',
                                        'label'         => 'Stat Label',
                                        'name'          => 'stat_label',
                                        'aria-label'    => '',
                                        'type'          => 'text',
                                        'instructions'  => '',
                                        'required'      => 0,
                                        'conditional_logic' => false,
                                        'wrapper'       => [
                                            'width' => '50',
                                            'class' => '',
                                            'id'    => '',
                                        ],
                                        'placeholder'   => "e.g. Projects Completed",
                                        'default_value' => '',
                                        'maxlength'     => '',
                                        'prepend'       => '',
                                        'append'        => '',
                                        'parent_repeater' => 'field_rms_cta_v3_stats',
                                    ],
                                ],
                            ],
                        ],
                    ],
                    'layout_faq_v1' => [
                        'key'        => 'layout_faq_v1',
                        'name'       => 'faq-v1',
                        'label'      => 'FAQ V1',
                        'display'    => 'block',
                        'sub_fields' => [
                            [
                                'key'           => 'field_rms_faq_v1_headline',
                                'label'         => 'Headline',
                                'name'          => 'faq_v1_headline',
                                'type'          => 'text',
                                'wrapper'       => ['width' => '50'],
                                'placeholder'   => 'e.g. Frequently Asked Questions',
                            ],
                            [
                                'key'           => 'field_rms_faq_v1_subheadline',
                                'label'         => 'Subheadline',
                                'name'          => 'faq_v1_subheadline',
                                'type'          => 'text',
                                'wrapper'       => ['width' => '50'],
                                'placeholder'   => 'e.g. Get Answers to Common Roofing Questions',
                            ],
                            [
                                'key'           => 'field_rms_faq_v1_faqs',
                                'label'         => 'FAQ Items',
                                'name'          => 'faq_v1_faqs',
                                'type'          => 'repeater',
                                'layout'        => 'block',
                                'button_label'  => 'Add FAQ',
                                'sub_fields'    => [
                                    [
                                        'key'           => 'field_rms_faq_v1_question',
                                        'label'         => 'Question',
                                        'name'          => 'faq_question',
                                        'type'          => 'text',
                                        'wrapper'       => ['width' => '50'],
                                        'placeholder'   => 'e.g. How much does a new roof cost?',
                                        'parent_repeater' => 'field_rms_faq_v1_faqs',
                                    ],
                                    [
                                        'key'           => 'field_rms_faq_v1_answer',
                                        'label'         => 'Answer',
                                        'name'          => 'faq_answer',
                                        'type'          => 'wysiwyg',
                                        'tabs'          => 'visual',
                                        'toolbar'       => 'basic',
                                        'media_upload'  => 0,
                                        'parent_repeater' => 'field_rms_faq_v1_faqs',
                                    ],
                                ],
                            ],
                        ],
                    ],
                    'layout_faq_v2' => [
                        'key'        => 'layout_faq_v2',
                        'name'       => 'faq-v2',
                        'label'      => 'FAQ V2',
                        'display'    => 'block',
                        'sub_fields' => [
                            [
                                'key'           => 'field_rms_faq_v2_headline',
                                'label'         => 'Headline',
                                'name'          => 'faq_v2_headline',
                                'type'          => 'text',
                                'wrapper'       => ['width' => '50'],
                                'placeholder'   => 'e.g. Frequently Asked Questions',
                            ],
                            [
                                'key'           => 'field_rms_faq_v2_subheadline',
                                'label'         => 'Subheadline',
                                'name'          => 'faq_v2_subheadline',
                                'type'          => 'text',
                                'wrapper'       => ['width' => '50'],
                                'placeholder'   => 'e.g. Everything You Need to Know',
                            ],
                            [
                                'key'           => 'field_rms_faq_v2_faqs',
                                'label'         => 'FAQ Items',
                                'name'          => 'faq_v2_faqs',
                                'type'          => 'repeater',
                                'layout'        => 'block',
                                'button_label'  => 'Add FAQ',
                                'sub_fields'    => [
                                    [
                                        'key'           => 'field_rms_faq_v2_question',
                                        'label'         => 'Question',
                                        'name'          => 'faq_question',
                                        'type'          => 'text',
                                        'wrapper'       => ['width' => '50'],
                                        'placeholder'   => 'e.g. How much does a new roof cost?',
                                        'parent_repeater' => 'field_rms_faq_v2_faqs',
                                    ],
                                    [
                                        'key'           => 'field_rms_faq_v2_answer',
                                        'label'         => 'Answer',
                                        'name'          => 'faq_answer',
                                        'type'          => 'wysiwyg',
                                        'tabs'          => 'visual',
                                        'toolbar'       => 'basic',
                                        'media_upload'  => 0,
                                        'parent_repeater' => 'field_rms_faq_v2_faqs',
                                    ],
                                ],
                            ],
                        ],
                    ],
                    'layout_gallery_grid' => [
                        'key'        => 'layout_gallery_grid',
                        'name'       => 'gallery-grid',
                        'label'      => 'Gallery Grid',
                        'display'    => 'block',
                        'sub_fields' => [
                            [
                                'key'           => 'field_rms_gallery_items',
                                'label'         => 'Gallery Items',
                                'name'          => 'gallery_items',
                                'type'          => 'repeater',
                                'layout'        => 'block',
                                'button_label'  => 'Add Image',
                                'sub_fields'    => [
                                    [
                                        'key'           => 'field_rms_gallery_thumbnail',
                                        'label'         => 'Thumbnail',
                                        'name'          => 'gallery_thumbnail',
                                        'type'          => 'image',
                                        'return_format' => 'url',
                                        'wrapper'       => ['width' => '33'],
                                        'parent_repeater' => 'field_rms_gallery_items',
                                    ],
                                    [
                                        'key'           => 'field_rms_gallery_full',
                                        'label'         => 'Full Size',
                                        'name'          => 'gallery_full',
                                        'type'          => 'image',
                                        'return_format' => 'url',
                                        'wrapper'       => ['width' => '33'],
                                        'parent_repeater' => 'field_rms_gallery_items',
                                    ],
                                    [
                                        'key'           => 'field_rms_gallery_label',
                                        'label'         => 'Label',
                                        'name'          => 'gallery_label',
                                        'type'          => 'text',
                                        'wrapper'       => ['width' => '34'],
                                        'placeholder'   => 'e.g. Commercial Roofing',
                                        'parent_repeater' => 'field_rms_gallery_items',
                                    ],
                                ],
                            ],
                        ],
                    ],
                    'layout_portfolio_v1' => [
                        'key'        => 'layout_portfolio_v1',
                        'name'       => 'portfolio-v1',
                        'label'      => 'Portfolio V1',
                        'display'    => 'block',
                        'sub_fields' => [
                            [
                                'key'           => 'field_rms_portfolio_v1_headline',
                                'label'         => 'Headline',
                                'name'          => 'portfolio_v1_headline',
                                'type'          => 'text',
                                'wrapper'       => ['width' => '50'],
                                'placeholder'   => 'e.g. Our Recent Projects',
                            ],
                            [
                                'key'           => 'field_rms_portfolio_v1_subheadline',
                                'label'         => 'Subheadline',
                                'name'          => 'portfolio_v1_subheadline',
                                'type'          => 'text',
                                'wrapper'       => ['width' => '50'],
                                'placeholder'   => 'e.g. Quality Work, Proven Results',
                            ],
                            [
                                'key'           => 'field_rms_portfolio_v1_projects',
                                'label'         => 'Projects',
                                'name'          => 'portfolio_v1_projects',
                                'type'          => 'repeater',
                                'layout'        => 'block',
                                'button_label'  => 'Add Project',
                                'sub_fields'    => [
                                    [
                                        'key'           => 'field_rms_portfolio_v1_image',
                                        'label'         => 'Image',
                                        'name'          => 'project_image',
                                        'type'          => 'image',
                                        'return_format' => 'url',
                                        'wrapper'       => ['width' => '50'],
                                        'parent_repeater' => 'field_rms_portfolio_v1_projects',
                                    ],
                                    [
                                        'key'           => 'field_rms_portfolio_v1_label',
                                        'label'         => 'Label',
                                        'name'          => 'project_label',
                                        'type'          => 'text',
                                        'wrapper'       => ['width' => '50'],
                                        'placeholder'   => 'e.g. Residential Roofing',
                                        'parent_repeater' => 'field_rms_portfolio_v1_projects',
                                    ],
                                ],
                            ],
                        ],
                    ],
                    'layout_portfolio_v2' => [
                        'key'        => 'layout_portfolio_v2',
                        'name'       => 'portfolio-v2',
                        'label'      => 'Portfolio V2',
                        'display'    => 'block',
                        'sub_fields' => [
                            [
                                'key'           => 'field_rms_portfolio_v2_headline',
                                'label'         => 'Headline',
                                'name'          => 'portfolio_v2_headline',
                                'type'          => 'text',
                                'wrapper'       => ['width' => '50'],
                                'placeholder'   => 'e.g. Featured Work',
                            ],
                            [
                                'key'           => 'field_rms_portfolio_v2_subheadline',
                                'label'         => 'Subheadline',
                                'name'          => 'portfolio_v2_subheadline',
                                'type'          => 'text',
                                'wrapper'       => ['width' => '50'],
                                'placeholder'   => 'e.g. Browse Our Best Projects',
                            ],
                            [
                                'key'           => 'field_rms_portfolio_v2_projects',
                                'label'         => 'Projects',
                                'name'          => 'portfolio_v2_projects',
                                'type'          => 'repeater',
                                'layout'        => 'block',
                                'button_label'  => 'Add Project',
                                'sub_fields'    => [
                                    [
                                        'key'           => 'field_rms_portfolio_v2_image',
                                        'label'         => 'Image',
                                        'name'          => 'project_image',
                                        'type'          => 'image',
                                        'return_format' => 'url',
                                        'wrapper'       => ['width' => '50'],
                                        'parent_repeater' => 'field_rms_portfolio_v2_projects',
                                    ],
                                    [
                                        'key'           => 'field_rms_portfolio_v2_label',
                                        'label'         => 'Label',
                                        'name'          => 'project_label',
                                        'type'          => 'text',
                                        'wrapper'       => ['width' => '50'],
                                        'placeholder'   => 'e.g. Residential Roofing',
                                        'parent_repeater' => 'field_rms_portfolio_v2_projects',
                                    ],
                                ],
                            ],
                        ],
                    ],
                    'layout_portfolio_v3' => [
                        'key'        => 'layout_portfolio_v3',
                        'name'       => 'portfolio-v3',
                        'label'      => 'Portfolio V3',
                        'display'    => 'block',
                        'sub_fields' => [
                            [
                                'key'           => 'field_rms_portfolio_v3_headline',
                                'label'         => 'Headline',
                                'name'          => 'portfolio_v3_headline',
                                'type'          => 'text',
                                'wrapper'       => ['width' => '50'],
                                'placeholder'   => 'e.g. Project Gallery',
                            ],
                            [
                                'key'           => 'field_rms_portfolio_v3_subheadline',
                                'label'         => 'Subheadline',
                                'name'          => 'portfolio_v3_subheadline',
                                'type'          => 'text',
                                'wrapper'       => ['width' => '50'],
                                'placeholder'   => 'e.g. Explore Our Work by Category',
                            ],
                            [
                                'key'           => 'field_rms_portfolio_v3_filters',
                                'label'         => 'Filter Tabs',
                                'name'          => 'portfolio_v3_filters',
                                'type'          => 'repeater',
                                'layout'        => 'block',
                                'button_label'  => 'Add Filter',
                                'sub_fields'    => [
                                    [
                                        'key'           => 'field_rms_portfolio_v3_filter_label',
                                        'label'         => 'Filter Label',
                                        'name'          => 'filter_label',
                                        'type'          => 'text',
                                        'wrapper'       => ['width' => '100'],
                                        'placeholder'   => 'e.g. Residential',
                                        'parent_repeater' => 'field_rms_portfolio_v3_filters',
                                    ],
                                ],
                            ],
                            [
                                'key'           => 'field_rms_portfolio_v3_projects',
                                'label'         => 'Projects',
                                'name'          => 'portfolio_v3_projects',
                                'type'          => 'repeater',
                                'layout'        => 'block',
                                'button_label'  => 'Add Project',
                                'sub_fields'    => [
                                    [
                                        'key'           => 'field_rms_portfolio_v3_image',
                                        'label'         => 'Image',
                                        'name'          => 'project_image',
                                        'type'          => 'image',
                                        'return_format' => 'url',
                                        'wrapper'       => ['width' => '33'],
                                        'parent_repeater' => 'field_rms_portfolio_v3_projects',
                                    ],
                                    [
                                        'key'           => 'field_rms_portfolio_v3_label',
                                        'label'         => 'Label',
                                        'name'          => 'project_label',
                                        'type'          => 'text',
                                        'wrapper'       => ['width' => '33'],
                                        'placeholder'   => 'e.g. Residential Roofing',
                                        'parent_repeater' => 'field_rms_portfolio_v3_projects',
                                    ],
                                    [
                                        'key'           => 'field_rms_portfolio_v3_category',
                                        'label'         => 'Category',
                                        'name'          => 'project_category',
                                        'type'          => 'text',
                                        'wrapper'       => ['width' => '34'],
                                        'placeholder'   => 'e.g. residential',
                                        'instructions'  => 'Must match a filter tab value (lowercase).',
                                        'parent_repeater' => 'field_rms_portfolio_v3_projects',
                                    ],
                                ],
                            ],
                        ],
                    ],
                ],
                'button_label'   => 'Add Section',
                'min'            => '',
                'max'            => '',
            ],
        ],
        'location' => [
            [
                [
                    'param'    => 'page',
                    'operator' => '==',
                    'value'    => 'all',
                ],
            ],
        ],
        'menu_order'            => 0,
        'position'              => 'normal',
        'style'                 => 'default',
        'label_placement'       => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen'        => '',
        'active'                => true,
        'description'           => '',
        'show_in_rest'          => 0,
    ]);
}

add_action('acf/init', 'rms_register_acf_page_sections');
